### PR TITLE
Implementation of MONGO_URL for possibility to run tests via `MONGO_U…

### PR DESCRIPTION
**Pull request by mrusme**
Implementation of MONGO_URL for possibility to run tests via `MONGO_URL=mongodb://192.168.99.100:32768/mongorito_test npm test`

### CODE REVIEW

**Comment by mrusme** [comment]
@vdemedes not sure what's wrong with Travis as `npm test` returns successfully on my local machine.

**Comment by vdemedes** [comment]
I'm against this change, as this check could happen before `Mongorito.connect()` and a final URL passed over there.

```js
const url = process.env.MONGODB_URL || defaultUrl;
Mongorito.connect(url);
```

Simple enough and does not require any modification.

**Comment by mrusme** [comment]
@vdemedes could you please point me to the location inside Mongorito, where the MONGODB_URL is being read? I grepped for "MONGODB_URL" and couldn't find anything in the source-code:

```
Searching 31 files for "MONGODB_URL"

0 matches
```

**Comment by vdemedes** [comment]
Oh, sorry, I was on mobile and misunderstood the changes being made. Thanks ;)

**Pull request merged**
