### PR TITLE
Make findById work with populate

### PR DESCRIPTION
**Pull request by YoussefKababe**
I know I can use findOne, but I find findById to be simpler...

### CODE REVIEW

**Comment by vdemedes** [comment]
Could you provide an example code on how you use this method? Because `findById` was never meant to be attached to `Query` class.

**Comment by YoussefKababe** [comment]
I have a bunch of products that have a reference to their categories, I want to query the product with its category populated:

```javascript
// productsController.js

...
// route: /api/products/:id
one: function(req, res) {
    co(function*() {
      var product = yield Product.populate('category', Category).findOne({ _id: req.params.id })
      // I think the line above can be like this:
      // var product = yield Product.populate('category', Category).findById(req.params.id)
      res.json({ product: product })
    })
  },
...
```

**Comment by vdemedes** [comment]
Oh right, good point. Thanks!

**Comment by vdemedes** [comment]
Released on npm as `mongorito@1.4.1`.

**Comment by YoussefKababe** [comment]
Thank you @vdemedes! And also thank you so much for Mongorito! (ex. Mongoose user)

**Comment by vdemedes** [comment]
@YoussefKababe I am really really glad you like it!

**Pull request merged**
